run:
  timeout: 5m
  tests: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocritic
    - gocyclo
    - goheader
    - goimports
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - misspell
    - musttag
    - nakedret
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - whitespace
    - zerologlint

linters-settings:
  gocyclo:
    min-complexity: 15
  
  lll:
    line-length: 120
  
  goimports:
    local-prefixes: go_platform_template
  
  revive:
    rules:
      - name: exported
        severity: error

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
