run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck        # Check error handling
    - errchkjson      # Check JSON error handling
    - govet           # Go vet
    - typecheck       # Type checking
    - gosec           # Security issues
    - staticcheck     # Static analysis
    - unconvert       # Unnecessary type conversions
    - unused          # Unused variables
    - sqlclosecheck   # SQL connection closing

linters-settings:
  revive:
    rules:
      - name: exported
        severity: error

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
